### ISSUE TITLE
Crash with better crashes mod.

### ISSUE THREAD

**Issue by jklw10** [WittyWhiscash/DamageOverhaul#3] opened 2021-03-17 12:05 UTC
[crash-2021-03-17_14.01.09-client.txt](https://github.com/WittyWhiscash/DamageOverhaul/files/6156214/crash-2021-03-17_14.01.09-client.txt)

complains about entry point main having errors.

**Comment by WittyWhiscash** [comment] 2021-03-17 18:07
Does not appear to be caused by my mod. A more likely culprit is OneBar by madis0, and their config not being registered properly. Will report this to them.

**Comment by WittyWhiscash** [comment] 2021-03-17 19:37
Seems they pushed a fix for their mod. Try version `1.2.1` of OneBar and see if this fixes the issue. Open up the issue [here](https://github.com/Madis0/OneBar/issues/11) if the error persists.

**Comment by jklw10** [comment] 2021-03-18 05:57
how did you find out it was his mod that crashed? I seem to be getting the same end result in a new crash (updated Onebar to 1.2.1)
[crash-2021-03-18_07.52.08-client.txt](https://github.com/WittyWhiscash/DamageOverhaul/files/6161623/crash-2021-03-18_07.52.08-client.txt)
ah i see it made 2 logs here's the second log.
[crash-2021-03-18_08.40.49-server.txt](https://github.com/WittyWhiscash/DamageOverhaul/files/6161862/crash-2021-03-18_08.40.49-server.txt)
And this one has the main entry point failure in it.

**Comment by WittyWhiscash** [comment] 2021-03-18 15:19
Thanks for providing me with the main entrypoint failure in it. I see exactly what is going on. Will push a fix for this very soon.

**Comment by WittyWhiscash** [comment] 2021-03-18 15:42
Should hopefully be fixed in `1.0.0-BETA3`. I apologize for the inconvenience. Thanks for reporting! Reopen this issue if it persists.

**Closed as completed by WittyWhiscash** 2021-03-18 15:42 UTC
