### ISSUE TITLE
Crash with Age of Exile

### ISSUE THREAD

**Issue by jklw10** [WittyWhiscash/DamageOverhaul#4] opened 2021-03-19 14:00 UTC
it is i. the bringer of bad news :)
https://gist.githubusercontent.com/natanfudge/bccca05586fcb14892a904b526b75ec8/raw/40682864c499bb9dd801d328cc188bc4aeb7e98c/crash.txt

**Comment by WittyWhiscash** [comment] 2021-03-19 18:46
Thanks for reporting!

I think I see/suspect what is going on, but for confirmation, can you reproduce the crash with verbose logging on (in the config screen, under Debug, enable Damage Debug) and post the latest.log here as well from when it crashed? If the logging functions are on and working correctly, I'll be more able to diagnose what is going on.

My current suspicion is that the nature_zombie entity took some sort of environmental damage, being fall, fire or lava most likely. If my suspicions are correct, I failed to add another check in the LivingEntity/PlayerEntity mixin that checks if the damaged entity has a resistance spread as well for environmental damage. Therefore, because the entity doesn't have a database entry, when the resistance spread is checked in my custom logic, it returns null.

**Comment by jklw10** [comment] 2021-03-24 11:03
oh. the crash is onload so i'm going to have to manually change the config in the files. results soon:tm:

**Comment by jklw10** [comment] 2021-03-24 11:26
damageDebug was true by default.
[latest.log](https://github.com/WittyWhiscash/DamageOverhaul/files/6196645/latest.log)

**Comment by WittyWhiscash** [comment] 2021-04-11 23:02
Sorry for being late on the follow up here. 

While it appears the main and original issue you reported is resolved in `1.0.0-BETA4`, I do not think the other crash, the one on load, is caused by my mod. 

It appears to be a fundamental incompatibility between Creeper AI Updated (modid creeperaiupdated) and Health Blast (modid healthblast) as they both attempt to redirect the same method. Redirects are tough, because if both mods redirect the same method, they are fundamentally incompatible. I'd recommend using one or the other, and reporting this to the mod authors.

**Closed as completed by WittyWhiscash** 2021-04-11 23:02 UTC
Labels: bug
